version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mobile-money-mysql
    environment:
      MYSQL_DATABASE: mobile_money
      MYSQL_USER: mobile
      MYSQL_PASSWORD: mobile123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: mobile-money-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mobile_money
      SPRING_DATASOURCE_USERNAME: mobile
      SPRING_DATASOURCE_PASSWORD: mobile123

volumes:
  mysql_data:
